language: node_js
sudo: false
node_js:
  - '6.11'
  - '7.9'
  - 'node'
install:
- git fetch --unshallow --all
- npm install -g codecov
- npm install -g istanbul
script:
 - codecov
after_script:
  - npm run coveralls
env:
  global:
    - secure: "aK5LIuEs6Vwb9CZ5VSob/EAk8XFqT4XRxXavs1SF1eeg7nuL38TNReDQ9+fRJrEm1kQEnkzWg5L9KHdj+AliyJF+niphafqwkui1mSdj6RwvBkj2EmzZoGeJE0BoDxXmWInPStRgj3DDc6ONhhCS9yegjYDyimRNQVuO5glOFX4="
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
    git config --global user.name "gulp-msbuild"
    echo -e "machine github.com\n login gulp-msbuild\n password $GITHUB_TOKEN" >> ~/.netrc
  fi
 
